# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  database: db_seriendb
  pool: 5
  username: dbu_seriendb
  password: hallo
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: db_seriendb
  pool: 5
  username: dbu_seriendb
  password: gopedo15
  host: localhost
